micronaut:
  application:
    name: com.budgeteer.api
  server:
    cors:
      enabled: true
  router:
    static-resources:
      default:
        enabled: true
        mapping: "/**"
        paths: "classpath:public"
  security:
    enabled: true
    authentication: bearer
    endpoints:
      login:
        enabled: true
        path: ${api.base-path}/login
    token:
      jwt:
        bearer:
          enabled: true
        signatures:
          secret:
            generator:
              secret: ${JWT_SIGNATURE_SECRET:CHANGEMECHANGEMECHANGEMECHANGEME}
              jws-algorithm: HS256
        enabled: true
    reject-not-found: false
    intercept-url-map:
      -
        pattern: ${api.base-path}/users
        http-method: POST
        access:
          isAnonymous()
      -
        pattern: ${api.base-path}/login
        http-method: POST
        access:
          isAnonymous()
      -
        pattern: ${api.base-path}/**
        access:
          isAuthenticated()
      -
        pattern: /**
        access:
          - isAnonymous()
          - isAuthenticated()

datasources:
  default:
    # TODO: figure out how to configure url by OS
    # TODO: encrypt for non-dev env
    url: ${JDBC_URL:`jdbc:h2:./data/db:default;DB_CLOSE_DELAY=1;DB_CLOSE_ON_EXIT=FALSE;database_to_upper=false`}
    username: ${JDBC_USER:dev_user}
    password: ${JDBC_PASSWORD:dev_filepswd dev_dbpswd}
    driverClassName: ${JDBC_DRIVER:org.h2.Driver}
    schema-generate: none

jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: none
        show_sql: false
        jdbc:
          fetch_size: 100
          batch_size: 30
          order_inserts: true
          order_updates: true
        bytecode:
          use_reflection_optimizer: true
          provider: javassist

flyway:
  datasources:
    default:
      enabled: true
      locations: classpath:migrations

jackson:
  date-format: ${DATE_FORMAT:yyyy-MM-dd'T'HH:mm:ss}

api:
  base-path: /api
