FROM node:lts-alpine as build-stage
WORKDIR /app
COPY ./client/package*.json ./
ARG VUE_APP_API_HOST
ENV VUE_APP_API_HOST $VUE_APP_API_HOST
ARG VUE_APP_API_BASE_PATH
ENV VUE_APP_API_BASE_PATH $VUE_APP_API_BASE_PATH
RUN npm install
COPY ./client .
RUN npm run build

FROM nginx:stable-alpine as production-stage
COPY --from=build-stage /app/dist /usr/share/nginx/html
COPY ./docker/nginx/nginx.conf /etc/nginx/nginx.conf
EXPOSE 8080
CMD ["nginx", "-g", "daemon off;"]