FROM gradle:6.8.3-jdk11 AS build
COPY --chown=gradle:gradle ./api /home/gradle/src
WORKDIR /home/gradle/src
RUN gradle shadowJar --no-daemon

FROM openjdk:11

EXPOSE 8081

RUN mkdir /app

COPY --from=build /home/gradle/src/build/libs/budget-app.jar /app/budget-app.jar

ENTRYPOINT ["java", "-jar","/app/budget-app.jar"]