# This workflow will check against checkstyle

name: Java Checkstyle with Gradle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-checks:

    runs-on: ubuntu-latest
    env:
      working-directory: ./api
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11.0.10
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      working-directory: ${{env.working-directory}}
    - name: Run checkstyle 
      run: ./gradlew checkstyleMain
      working-directory: ${{env.working-directory}}