# This workflow will check against unit tests and checkstyle

name: Java CI with Gradle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-checks:

    runs-on: ubuntu-latest
    env:
      working-directory: ./api
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11.0.10
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      working-directory: ${{env.working-directory}}
    - name: Run checkstyle 
      run: ./gradlew checkstyleMain
      working-directory: ${{env.working-directory}}
    - name: Run Tests
      run: ./gradlew test
      working-directory: ${{env.working-directory}}
    - name: Publish Unit Test Results
      uses: EnricoMi/publish-unit-test-result-action@v1.7
      if: always()
      with:
        comment_title: JUnit test Statistics
        github_token: ${{ secrets.GITHUB_TOKEN }}
        files: ./api/build/test-results/**/*.xml
